openapi: 3.0.0
info:
  title: Documentación de la API de Carritos
  version: 1.0.0
  description: Documentación de los endpoints de carritos de la API

paths:
  /carts:
    get:
      summary: Obtener todos los carritos
      tags:
        - Carts            
      description: Obtiene una lista de todos los carritos disponibles.
      parameters:
        - name: limit
          in: query
          description: Número máximo de carritos a obtener (opcional).
          schema:
            type: integer
      responses:
        '200':
          description: Respuesta exitosa
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Cart'

  /carts/:cid:
    get:
      summary: Obtener productos de un carrito por ID
      tags:
        - Carts      
      description: Obtiene los productos de un carrito específico por su ID.
      parameters:
        - name: cid
          in: path
          required: true
          description: ID del carrito a buscar.
          schema:
            type: string
      responses:
        '200':
          description: Respuesta exitosa
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CartWithProducts'
        '404':
          description: Carrito no encontrado

components:
  schemas:
    Cart:
      type: object
      properties:
        _id:
          type: string
          description: ID del carrito.
        products:
          type: array
          items:
            type: object
            properties:
              idProduct:
                type: string
                description: ID del producto en el carrito.
              quantity:
                type: number
                description: Cantidad del producto en el carrito.

    CartWithProducts:
      type: object
      properties:
        _id:
          type: string
          description: ID del carrito.
        products:
          type: array
          items:
            $ref: '#/components/schemas/Product'

    Product:
      type: object
      properties:
        title:
          type: string
          description: Título del producto.
        description:
          type: string
          description: Descripción del producto.
        code:
          type: number
          description: Código del producto.
        price:
          type: number
          format: float
          description: Precio del producto.
        status:
          type: boolean
          description: Estado del producto.
        stock:
          type: number
          description: Stock del producto.
        category:
          type: string
          description: Categoría del producto.
        thumbnail:
          type: string
          description: URL de la imagen del producto.
        owner:
          type: string
          description: Propietario del producto.
        quantity:
          type: number
          description: Cantidad del producto en el carrito.



# openapi: 3.0.0
# info:
#   title: Documentación de la API de Carritos
#   version: 1.0.0
#   description: Documentación de los endpoints de carritos de la API

# paths:
#   /carts:
#     get:
#       summary: Obtener todos los carritos
#       tags:
#         - Carts      
#       description: Obtiene una lista de todos los carritos disponibles.
#       parameters:
#         - name: limit
#           in: query
#           description: Número máximo de carritos a obtener (opcional).
#           schema:
#             type: integer
#       responses:
#         '200':
#           description: Respuesta exitosa
#           content:
#             application/json:
#               schema:
#                 type: array
#                 items:
#                   $ref: '#/components/schemas/Cart'

#   /carts/:cid:
#     get:
#       summary: Obtener productos de un carrito por ID
#       tags:
#         - Carts        
#       description: Obtiene los productos de un carrito específico por su ID.
#       parameters:
#         - name: cid
#           in: path
#           required: true
#           description: ID del carrito a buscar.
#           schema:
#             type: string
#       responses:
#         '200':
#           description: Respuesta exitosa
#           content:
#             application/json:
#               schema:
#                 $ref: '#/components/schemas/CartWithProducts'
#         '404':
#           description: Carrito no encontrado

# components:
#   schemas:
#     Cart:
#       type: object
#       properties:
#         _id:
#           type: string
#           description: ID del carrito.
#         products:
#           type: array
#           items:
#             type: object
#             properties:
#               idProduct:
#                 type: string
#                 description: ID del producto en el carrito.
#               quantity:
#                 type: number
#                 description: Cantidad del producto en el carrito.

#     CartWithProducts:
#       type: object
#       properties:
#         _id:
#           type: string
#           description: ID del carrito.
#         products:
#           type: array
#           items:
#             $ref: '#/components/schemas/Product'

#     Product:
#       type: object
#       properties:
#         title:
#           type: string
#           description: Título del producto.
#         description:
#           type: string
#           description: Descripción del producto.
#         code:
#           type: number
#           description: Código del producto.
#         price:
#           type: number
#           format: float
#           description: Precio del producto.
#         status:
#           type: boolean
#           description: Estado del producto.
#         stock:
#           type: number
#           description: Stock del producto.
#         category:
#           type: string
#           description: Categoría del producto.
#         thumbnail:
#           type: string
#           description: URL de la imagen del producto.
#         owner:
#           type: string
#           description: Propietario del producto.
