openapi: 3.0.0
info:
  title: Documentación de la API de Usuarios
  version: 1.0.0
  description: Documentación de los endpoints de usuarios de la API

paths:
  /users:
    get:  
      summary: Obtiene una lista de todos los usuarios
      tags:
        - Users
      description: Obtiene una lista de todos los usuarios.
      responses:
        '200':
          description: Lista de usuarios

  /usersDTO:
    get:  
      summary: Obtiene una lista de todos los usuarios con sus DTO
      tags:
        - Users
      description: Obtiene una lista de todos los usuarios con sus DTO.
      responses:
        '200':
          description: Lista de usuarios con DTO

  /deleteInactiveUsers:
    delete:  
      summary: Elimina a los usuarios inactivos
      tags:
        - Users
      description: Elimina a los usuarios inactivos.
      responses:
        '200':
          description: Usuarios inactivos eliminados
